language: python
dist: xenial
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9
install:
  - pip3 install pylint
script:
  - pylint coverage2css.py
  - cd tests/
  - python3 ../coverage2css.py Coverage-example.json home-style.min.css
  - diff home-style.min.css.new home-style.min.css.expected
